version: '3'
services:
  back-end:
    build: ./ms-nest
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      ARGON_SALT: ${ARGON_SALT}
