version: '3'
services:
  ms-nest:
    build: ms-nest
    image: ms-nest
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      ARGON_SALT: ${ARGON_SALT}
      BRIDGE_SECRET: ${BRIDGE_SECRET}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      MS_DATA_URL: ${MS_DATA_URL}

  ms-data:
    build: ms-data
    image: ms-data
    environment:
      BRIDGE_SECRET: ${BRIDGE_SECRET}
