services:
  - type: web
    name: nest_v1
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./ms-nest/Dockerfile
    dockerContext: ./ms-nest
    envVars:
      - fromGroup: cryptopilot-env


  - type: web
    name: ml_v1
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./ms-data/Dockerfile
    dockerContext: ./ms-data
    envVars:
      - fromGroup: cryptopilot-env
