FROM python:3.11-alpine

WORKDIR /app

COPY ./ /app

RUN apk update
RUN apk add --no-cache make automake gcc g++ subversion python3-dev
RUN pip install -r requirements.txt

EXPOSE 4040

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4040" ]