name: DB clean up cron job

on:
  schedule:
    - cron: "00 */6 * * *"
  
jobs:
  clean-up:
    name: make a DB clean up request
    runs-on: ubuntu-latest
    
    steps:
      - name: curl request
        run: curl https://nest-v1.onrender.com/auth/clean-up