name: DB push
  
on:
  push:
    branches:
      - main
    paths:
      - 'ms-nest/*'

jobs:
  push-new-db-scheme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: change directory to `ms-nest`
        run: cd ms-nest

      - name: push scheme
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
      
  
